services:
  - type: web
    name: chatbot-service
    env: python
    plan: free
    branch: main
    rootDir: chatbot
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    pythonVersion: 3.10.13
